steps:
  # ==============================================================================
  # 1. BUILD IMAGES
  # ==============================================================================
  
  # Processor (Builds from Root Context)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Processor'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/processor:latest', '-f', 'processor/Dockerfile', '.']

  # Aggregator (Builds from Root Context)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Aggregator'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/aggregator:latest', '-f', 'aggregator/Dockerfile', '.']

  # Media Processor (Builds from Directory Context)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Media Processor'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/media-processor:latest', './media-processor']

  # ==============================================================================
  # 2. PUSH IMAGES
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Images'
    args: ['push', 'gcr.io/$PROJECT_ID/processor:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aggregator:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/media-processor:latest']

  # ==============================================================================
  # 3. DEPLOY CLOUD RUN JOBS
  # ==============================================================================
  
  # Deploy Processor Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'jobs', 'deploy', 'processor-job', '--image', 'gcr.io/$PROJECT_ID/processor:latest', '--region', 'us-central1', '--tasks', '1', '--max-retries', '0']

  # Deploy Aggregator Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'jobs', 'deploy', 'aggregator-job', '--image', 'gcr.io/$PROJECT_ID/aggregator:latest', '--region', 'us-central1', '--tasks', '1', '--max-retries', '0']

  # Deploy Media Processor Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'jobs', 'deploy', 'media-processor-job', '--image', 'gcr.io/$PROJECT_ID/media-processor:latest', '--region', 'us-central1', '--tasks', '1', '--max-retries', '0']

images:
- 'gcr.io/$PROJECT_ID/processor:latest'
- 'gcr.io/$PROJECT_ID/aggregator:latest'
- 'gcr.io/$PROJECT_ID/media-processor:latest'
