steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Splitter'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/splitter:${_SHORT_SHA}', './splitter']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Processor'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/processor:${_SHORT_SHA}', './processor']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Aggregator'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/aggregator:${_SHORT_SHA}', './aggregator']
  
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Dispatcher'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/dispatcher:${_SHORT_SHA}', './dispatcher']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Media Processor'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/media-processor:${_SHORT_SHA}', './media-processor']

images:
- 'gcr.io/${_PROJECT_ID}/splitter:${_SHORT_SHA}'
- 'gcr.io/${_PROJECT_ID}/processor:${_SHORT_SHA}'
- 'gcr.io/${_PROJECT_ID}/aggregator:${_SHORT_SHA}'
- 'gcr.io/${_PROJECT_ID}/dispatcher:${_SHORT_SHA}'
- 'gcr.io/${_PROJECT_ID}/media-processor:${_SHORT_SHA}'

substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _SHORT_SHA: 'latest'
